### ISSUE TITLE
About AUTH extension feature

### ISSUE THREAD

**Issue by yanhu123** [leopku/SendmailViaSMTP#1]
The authentication mechanisms contain __LOGIN DIGEST-MD5 PLAIN__, but when I catch a mail transfer package by wireshark, it shows that the __AUTH CRAM-MD5__.

__Two issues:__
  * How can I choose the authentication method?
  * Where does the CRAM-MD5 come from?

**Comment by leopku** [comment]
Hi @yanhu123,

Try change 132 line of SendmailViaSMTP https://github.com/leopku/SendmailViaSMTP/blob/master/SendmailViaSMTP.py#L132 from

```
'LOGIN DIGEST-MD5 PLAIN'
```
to
```
'LOGIN CRAM-MD5 PLAIN'
```

or and CRAM into the list
```
'LOGIN DIGEST-MD5 CRAM-MD5 PLAIN'
```

I will be grateful if feed back.
